language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - PLUGIN_NAME=TinyMCE
    - DB=mysql
    - REQUIRE="phpunit/phpunit:3.7.31"

  matrix:
    - DB=mysql CAKE_VERSION=master COVERALLS=1

matrix:
  include:
    - php: 5.6
      env:
        - CAKE_VERSION=master
    - php: 7.0
      env:
        - CAKE_VERSION=master
    - php: 7.1
      env:
        - CAKE_VERSION=master
    - php: 7.2
      env:
        - CAKE_VERSION=master
    - php: 7.3
      env:
        - CAKE_VERSION=master
    - php: 7.4
      env:
        - CAKE_VERSION=master

before_script:
  - git clone https://github.com/burzum/travis.git --depth 1 ../travis
  - ../travis/before_script.sh
  - if [ "$PHPCS" != 1 ]; then
            echo "
                require_once APP . DS . 'vendor' . DS . 'phpunit' . DS . 'phpunit' . DS . 'PHPUnit' . DS . 'Autoload.php';
            " >> ../cakephp/app/Config/bootstrap.php;
    fi

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
